### ISSUE TITLE
Round function to get same result as in the thermostat

### ISSUE THREAD

**Issue by Qxlkdr** [abondoe/touchline#1]
First of all, very nice work!

Right now I can get 22.05 via the library as current temperature. However use the some kind of "round function" to get the same result as from the thermostat (22.1).

I have no Python skills yet, but in Home Assistant you can use:
`value_template: '{{ value | multiply(0.01) | round(1) }}'`

Got to be some way to get the same result via Python.

**Comment by abondoe** [comment]
Hi Qxlkdr!

Thanks for testing. This can be achieved with round(number, 1). I’ll implement this for the next release.
